### PR TITLE
fix: implement affiliate section changes and tooltip feature

### LINKED ISSUE #21: New unclaimed revenue & marketing toolkip section
## Description 📹

Loom: [https://www.loom.com/share/3c54149a25264710a0ad8c926bc1b07a](https://www.loom.com/share/3c54149a25264710a0ad8c926bc1b07a)

There are two new cards: one for claiming earnings (if the user has any) and another to download the Starknet ID toolkit for marketing. Add tooltip also by hovering the icon info.

Current section:  
image  
image

New section:  
[https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1](https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1)  
image

## Proposed Actions 🛠️

Here's a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   [Propose the changes you would like to see in the code]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Favvie**
- Added the unclaimed revenue section
- Added marketing toolkit section
- Implemented the custom cursor 
- Added tooltip

Close #21

### CODE REVIEW

**Review by fricoben — CHANGES_REQUESTED** [review]
## E2E Review 

Code looks OK but some features are missing here. 

Capture d’écran 2024-11-28 à 09 56 10

- [ ] You made the new version but didn't delete the old version ?

Capture d’écran 2024-11-28 à 09 54 14

- [ ] These 2 buttons don't do anything except sending to a random link we need them to respectively claim the money sitted on the contract and download the media KIT as the two buttons of the old version did (you can take the same code logic just apply it to these button)

**Comment by Favvie** [comment]
I removed the "unclaimed revenue", "get help from your affiliation manager" and "marketing toolkit at your fingertips" section. 
I utilized the existing remainingBalance functionality to display the correct balance.

**Review by fricoben — CHANGES_REQUESTED** [review]
Capture d’écran 2024-11-29 à 10 09 38
Capture d’écran 2024-11-29 à 10 09 43

`Claim` button doesn't check the state of the contract, if I have nothing to claim you should make the button disabled like it was before (and say on the button `Nothing too claim`)

**Review by fricoben — APPROVED** [review]
lgtm

**Pull request merged**
