### PR TITLE
Fix #22 : Refont of FAQ section

### LINKED ISSUE #22: Refont of FAQ section
## Description 📹

Loom: [https://www.loom.com/share/ff249906156e4977b17c70e74f256325](https://www.loom.com/share/ff249906156e4977b17c70e74f256325)

We made various design-only adjustments to the FAQ section, but the functionality remains the same. We placed the title at the top and added a subtitle. We also adjusted the text size, changed the divider color, and reduced the padding.

Old section:  
image

New section:  
[https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1](https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=3555-6782&t=x8xvLBhT37BVQyXF-1)  
image

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by SudiptaPaul-31**
Close #22

### CODE REVIEW

**Comment by SudiptaPaul-31** [comment]
@fricoben please review

**Comment by SudiptaPaul-31** [comment]
@fricoben Please review

**Comment by SudiptaPaul-31** [comment]
@fricoben @Kevils  please review

**Review by fricoben — CHANGES_REQUESTED** [review]
Capture d’écran 2024-11-23 à 21 44 13

Don't center and we're good !

**Comment by SudiptaPaul-31** [comment]
@fricoben Please have a look

**Review by fricoben — APPROVED** [review]
lgtm

**Pull request merged**
